### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by lufizyang** [chnsh/DCRNN_PyTorch#2]
I was running: 

   python run_demo_pytorch.py --config_filename=data/model/pretrained/METR-LA/config.yaml

This is what I got:

  Traceback (most recent call last):
  File "run_demo_pytorch.py", line 8, in <module>
    from model.pytorch.dcrnn_supervisor import DCRNNSupervisor
  File "C:\Users\mi\Desktop\DCRNN_PyTorch-pytorch_scratch\model\pytorch\dcrnn_supervisor.py", line 6, in <module>
    from torch.utils.tensorboard import SummaryWriter
ImportError: No module named 'torch.utils.tensorboard'

**Comment by chnsh** [comment]
oh, maybe you'll have to install tensorboard as well? Can you try after installing tensorboard
